### ISSUE TITLE
build fails on FreeBSD 11.1

### ISSUE THREAD

**Issue by dimpase** [google/python-subprocess32#43]
One gets 
```
    _posixsubprocess.c:764:22: error: use of undeclared identifier 'O_CLOEXEC'
        res = pipe2(fds, O_CLOEXEC);
```
while building the extension. The problem is that `O_CLOEXEC` defined in `fcntl.h` inside an `#if`, with the condition that does not hold true:
```
#if __POSIX_VISIBLE >= 200809
/* Defined by POSIX 1003.1-2008; BSD default, but reserve for future use. */
#define O_TTY_INIT      0x00080000      /* Restore default termios attributes */

#define O_CLOEXEC       0x00100000
#endif
```

To fix the build I ended up adding `-DO_CLOEXEC=0x00100000` to `CFLAGS`, after trying without success to do this more properly.

**Comment by gpshead** [comment]
Can you try out the PR I just made to see if that fixes this?

**Comment by dimpase** [comment]
OK, it builds on FreeBSD 11.1, and passes most tests; here are errors I see, not sure whether they are related to the issue, or not
```
FAIL: test_close_fds_when_max_fd_is_lowered (__main__.POSIXProcessTestCase)
Confirm that issue21618 is fixed (may fail under valgrind).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1866, in test_close_fds_when_max_fd_is_lowered
AssertionError: Some fds were left open.
:
======================================================================
FAIL: test_cloexec_pass_fds (__main__.POSIXSubprocessModuleTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 2257, in test_cloexec_pass_fds
AssertionError: '' != 'cat: /dev/fd/4: No such file or directory\n'
:
======================================================================
FAIL: test_close_fds_when_max_fd_is_lowered (__main__.ProcessTestCasePOSIXPurePython)
Confirm that issue21618 is fixed (may fail under valgrind).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1866, in test_close_fds_when_max_fd_is_lowered
AssertionError: Some fds were left open.
:
----------------------------------------------------------------------
Ran 291 tests in 253.214s
:
FAILED (failures=3, skipped=5)
Traceback (most recent call last):
  File "<stdin>", line 2420, in <module>
  File "<stdin>", line 2416, in test_main
  File "/usr/home/dima/Sage/sage/local/lib/python2.7/test/support/__init__.py", line 1577, in run_unittest
    _run_suite(suite)
  File "/usr/home/dima/Sage/sage/local/lib/python2.7/test/support/__init__.py", line 1542, in _run_suite
    raise TestFailed(err)
test.support.TestFailed: multiple errors occurred
```

**Comment by gpshead** [comment]
The errors are probably particular to FreeBSD vs what is being tested. Someone familiar with FreeBSD with a FreeBSD system in front of them should look at what those tests are trying to do decide what is appropriate there and submit a PR.  I'm happy to see it at least _building_ though. :)

**Comment by dimpase** [comment]
OK, so this is in the same state with 3.5.0 (builds, and tests error as described).
